# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: IDL.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'IDL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tIDL.proto\x12\nsimulacion\" \n\x0eRelojVectorial\x12\x0e\n\x06vector\x18\x01 \x03(\x05\"t\n\x0cMensajeEnvio\x12\x11\n\tid_emisor\x18\x01 \x01(\x05\x12\x13\n\x0bid_receptor\x18\x02 \x01(\x05\x12\x11\n\tcontenido\x18\x03 \x01(\t\x12)\n\x05reloj\x18\x04 \x01(\x0b\x32\x1a.simulacion.RelojVectorial\"l\n\x10MensajeRecepcion\x12\x11\n\tid_emisor\x18\x01 \x01(\x05\x12\x11\n\tcontenido\x18\x02 \x01(\t\x12\x32\n\x0ereloj_recibido\x18\x03 \x01(\x0b\x32\x1a.simulacion.RelojVectorial\"\x07\n\x05Vacio\"\x14\n\x03\x41\x63k\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x32\xfd\x01\n\x12ProcesoDistribuido\x12:\n\rEnviarMensaje\x12\x18.simulacion.MensajeEnvio\x1a\x0f.simulacion.Ack\x12?\n\x0eRecibirMensaje\x12\x1c.simulacion.MensajeRecepcion\x1a\x0f.simulacion.Ack\x12\x33\n\rEventoInterno\x12\x11.simulacion.Vacio\x1a\x0f.simulacion.Ack\x12\x35\n\x08\x44ifusion\x12\x18.simulacion.MensajeEnvio\x1a\x0f.simulacion.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IDL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELOJVECTORIAL']._serialized_start=25
  _globals['_RELOJVECTORIAL']._serialized_end=57
  _globals['_MENSAJEENVIO']._serialized_start=59
  _globals['_MENSAJEENVIO']._serialized_end=175
  _globals['_MENSAJERECEPCION']._serialized_start=177
  _globals['_MENSAJERECEPCION']._serialized_end=285
  _globals['_VACIO']._serialized_start=287
  _globals['_VACIO']._serialized_end=294
  _globals['_ACK']._serialized_start=296
  _globals['_ACK']._serialized_end=316
  _globals['_PROCESODISTRIBUIDO']._serialized_start=319
  _globals['_PROCESODISTRIBUIDO']._serialized_end=572
# @@protoc_insertion_point(module_scope)
