# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import IDL_pb2 as IDL__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in IDL_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcesoDistribuidoStub(object):
    """Servicios RPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarMensaje = channel.unary_unary(
                '/simulacion.ProcesoDistribuido/EnviarMensaje',
                request_serializer=IDL__pb2.MensajeEnvio.SerializeToString,
                response_deserializer=IDL__pb2.Ack.FromString,
                _registered_method=True)
        self.RecibirMensaje = channel.unary_unary(
                '/simulacion.ProcesoDistribuido/RecibirMensaje',
                request_serializer=IDL__pb2.MensajeRecepcion.SerializeToString,
                response_deserializer=IDL__pb2.Ack.FromString,
                _registered_method=True)
        self.EventoInterno = channel.unary_unary(
                '/simulacion.ProcesoDistribuido/EventoInterno',
                request_serializer=IDL__pb2.Vacio.SerializeToString,
                response_deserializer=IDL__pb2.Ack.FromString,
                _registered_method=True)
        self.Difusion = channel.unary_unary(
                '/simulacion.ProcesoDistribuido/Difusion',
                request_serializer=IDL__pb2.MensajeEnvio.SerializeToString,
                response_deserializer=IDL__pb2.Ack.FromString,
                _registered_method=True)


class ProcesoDistribuidoServicer(object):
    """Servicios RPC
    """

    def EnviarMensaje(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecibirMensaje(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventoInterno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Difusion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcesoDistribuidoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarMensaje': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarMensaje,
                    request_deserializer=IDL__pb2.MensajeEnvio.FromString,
                    response_serializer=IDL__pb2.Ack.SerializeToString,
            ),
            'RecibirMensaje': grpc.unary_unary_rpc_method_handler(
                    servicer.RecibirMensaje,
                    request_deserializer=IDL__pb2.MensajeRecepcion.FromString,
                    response_serializer=IDL__pb2.Ack.SerializeToString,
            ),
            'EventoInterno': grpc.unary_unary_rpc_method_handler(
                    servicer.EventoInterno,
                    request_deserializer=IDL__pb2.Vacio.FromString,
                    response_serializer=IDL__pb2.Ack.SerializeToString,
            ),
            'Difusion': grpc.unary_unary_rpc_method_handler(
                    servicer.Difusion,
                    request_deserializer=IDL__pb2.MensajeEnvio.FromString,
                    response_serializer=IDL__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulacion.ProcesoDistribuido', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simulacion.ProcesoDistribuido', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcesoDistribuido(object):
    """Servicios RPC
    """

    @staticmethod
    def EnviarMensaje(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulacion.ProcesoDistribuido/EnviarMensaje',
            IDL__pb2.MensajeEnvio.SerializeToString,
            IDL__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecibirMensaje(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulacion.ProcesoDistribuido/RecibirMensaje',
            IDL__pb2.MensajeRecepcion.SerializeToString,
            IDL__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventoInterno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulacion.ProcesoDistribuido/EventoInterno',
            IDL__pb2.Vacio.SerializeToString,
            IDL__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Difusion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulacion.ProcesoDistribuido/Difusion',
            IDL__pb2.MensajeEnvio.SerializeToString,
            IDL__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
